### ISSUE TITLE
discuss introduction content for episodes

### ISSUE THREAD

**Issue by mattstratton** [arresteddevops/ado-hugo#218]
Per DJL, while frontloading them all at the beginning makes it much easier for someone to skip them all at once, that isn't "doing right" by our sponsors. We don't want to make it EXTREMELY easy for our sponsors to be skipped.

Additionally, it takes a long time before we get to any content. We should introduce the topic as soon as possible (before sponsors are named for sure).

Inclusion of twitter handles in our self-introductions is a bit redundant; we can discuss if we keep doing this. It's done as a bit of our "brand", but I took that directly from The Ship Show, so it's not really our brand anyway.

**Comment by bridgetkromhout** [comment]
I participated in a podcast that recorded in approximately 3 15-minute chunks and they apparently do midroll. It kinda felt like it broke up the discussion a lot more than we usually would. Where were we thinking of putting the sponsors?

I would be cool with introducing the topic, then sponsor roll, then introducing the guests. We could record with the guest, then do the topic intro later and use pre-recorded sponsor stuff.

I don't think our twitter handles are all that necessary to say aloud because it's easy to find them in the @arresteddevops twitter profile.

**Comment by mattstratton** [comment]
I do think that the best of both worlds is probably to at least introduce the topic as soon as possible...right now people have to listen to about 1:45 before they even know what we are going to talk about.

**Comment by bridgetkromhout** [comment]
see Slack - I did a pretty extensive rewrite of the template.

**Comment by bridgetkromhout** [comment]
Are we happy now that we do some intro before we go to "a word from our sponsors"? Or does this need further review?

**Comment by mattstratton** [comment]
I think we are good for now :)
