### ISSUE TITLE
add guest landing page

### ISSUE THREAD

**Issue by bridgetkromhout** [arresteddevops/ado-hugo#530]
I checked out the first page of https://www.arresteddevops.com/guest; while (until you scroll down to the paginator) it's a good overview of our excellent past guests named Aaron, perhaps we could use a guest landing page that shows either a random or a curated set of guests, or perhaps info about being a guest, to assuage fears that we are an Aaron-centric podcast. 

![image](https://user-images.githubusercontent.com/2104453/116679727-8358d380-a970-11eb-8323-fd970f309703.png)

**Comment by mattstratton** [comment]
Heh. Yeah, if we wanted the behavior of this to change, I'll have to make a change to [castanet](httpa://github.com/mattstratton/castanet)

Random is actually pretty hard, because it's a static site generator, it would be random that only changed when the site was built (which basically means when a new episode is published). Curated might work a little better from a tech perspective, but then it needs to be curated. 

I'm leery of replacing it with a landing page saying how to be a guest, because:
- We don't need more ways of PR firms to find us 
- Despite not being an Aaron-centered podcast, a destination that lists all the guests is a feature I don't want to *remove*

Hmm.
